# Generated by Django 5.2.3 on 2025-07-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx')],
            },
        ),
    ]
